"""Adding community table

Revision ID: 121eaa5b4ac1
Revises: 2700cee765c9
Create Date: 2024-08-08 22:17:08.287526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121eaa5b4ac1'
down_revision = '2700cee765c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('members', sa.Integer(), nullable=False),
    sa.Column('impact_stories', sa.Text(), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('banner', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community')
    # ### end Alembic commands ###
