"""empty message

Revision ID: 1d88b873d1cb
Revises: d42a59bbd30f
Create Date: 2024-08-13 01:07:33.643050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d88b873d1cb'
down_revision = 'd42a59bbd30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
