"""empty message

Revision ID: 49008af76f28
Revises: fe58aa75b233
Create Date: 2024-08-11 13:44:21.604951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49008af76f28'
down_revision = 'fe58aa75b233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charity_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=256), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charity_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
