"""Remove username field from charity application

Revision ID: 5a724984dc9f
Revises: fa3774e0de9e
Create Date: 2024-08-11 21:17:50.871502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a724984dc9f'
down_revision = 'fa3774e0de9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charity_applications', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charity_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
