"""adding roles in charity and donor tables

Revision ID: b2f3ea2b084d
Revises: 5cc2cfc41e05
Create Date: 2024-08-09 12:48:12.545208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f3ea2b084d'
down_revision = '5cc2cfc41e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('charities', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
