"""Adding a category column in community table

Revision ID: dd1e8357b5ea
Revises: 121eaa5b4ac1
Create Date: 2024-08-09 00:12:28.854018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1e8357b5ea'
down_revision = '121eaa5b4ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
