"""Updating fields in charity application table

Revision ID: fa3774e0de9e
Revises: adb6a148f75c
Create Date: 2024-08-11 21:13:04.591966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3774e0de9e'
down_revision = 'adb6a148f75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charity_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charity_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('_password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
